# Generated by Django 4.0.5 on 2022-07-10 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.BigAutoField(db_column='Problem ID', primary_key=True, serialize=False)),
                ('problem_name', models.CharField(db_column='Problem Name', max_length=50)),
                ('problem_statement', models.CharField(db_column='Problem Statement', max_length=400)),
                ('problem_status', models.BooleanField(db_column='Solve_status', default=False)),
                ('problem_level', models.CharField(db_column='Problem level', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(max_length=200, upload_to='', verbose_name='Input')),
                ('output', models.CharField(max_length=200, verbose_name='Output')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.CharField(max_length=5000)),
                ('submitted_at', models.DateTimeField(verbose_name='Submitted on')),
                ('Verdict', models.CharField(blank=True, max_length=20, verbose_name='Verdict')),
                ('problem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OJ.problem')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
