# Generated by Django 4.0.5 on 2022-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_id',
            field=models.BigAutoField(db_column='Problem ID', primary_key=True, serialize=False),
        ),
    ]
