# Generated by Django 4.0.5 on 2022-07-10 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='solution',
            old_name='user_id',
            new_name='user',
        ),
    ]
