# Generated by Django 4.0.5 on 2022-06-30 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0002_alter_problems_problem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_code',
            field=models.FileField(blank=True, null=True, upload_to='./codeFiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
        migrations.AlterField(
            model_name='testcases',
            name='input',
            field=models.FileField(max_length=200, upload_to='', verbose_name='Input'),
        ),
    ]
