# Generated by Django 4.0.5 on 2022-06-30 10:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0003_alter_problems_problem_code_alter_testcases_input'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problems',
            name='problem_code',
            field=models.FileField(default=True, upload_to='codeFiles/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
    ]
