# Generated by Django 4.0.5 on 2022-07-02 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0004_alter_problems_problem_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problems',
            name='problem_code',
        ),
        migrations.AddField(
            model_name='solutions',
            name='problem_code',
            field=models.FileField(default=True, upload_to='Main\\OJ\\codeFiles', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
    ]
