# Generated by Django 4.0.5 on 2022-12-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0005_alter_testcase_input_alter_testcase_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='input',
            field=models.TextField(max_length=100000, verbose_name='Input'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output',
            field=models.TextField(max_length=100000, verbose_name='Output'),
        ),
    ]
