# Generated by Django 4.0.5 on 2022-07-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0005_remove_problems_problem_code_solutions_problem_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Problems',
            new_name='Problem',
        ),
        migrations.RenameModel(
            old_name='Solutions',
            new_name='Solution',
        ),
        migrations.RenameModel(
            old_name='TestCases',
            new_name='TestCase',
        ),
    ]
