# Generated by Django 4.0.5 on 2022-07-03 12:36

import OJ.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0006_rename_problems_problem_rename_solutions_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem_code',
            field=models.FileField(default=True, upload_to=OJ.models.content_file_name, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
    ]
