# Generated by Django 4.0.5 on 2022-07-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0007_alter_solution_problem_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='Verdict',
            field=models.CharField(blank=True, max_length=20, verbose_name='Verdict'),
        ),
    ]
