# Generated by Django 4.0.5 on 2022-07-04 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OJ', '0008_alter_solution_verdict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='problem_code',
            field=models.FileField(default=True, upload_to='media', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['cpp'])]),
        ),
    ]
